"""Export paper-ready LaTeX tables from failure taxonomy reports."""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from fsmreasonbench.evaluator.failure_taxonomy import TAXONOMY_CATEGORIES

DEFAULT_LATEX_CAPTION = (
    "Exploratory distribution of certificate failure categories in the F1 mixed "
    "capability-surface run."
)
DEFAULT_LATEX_LABEL = "tab:f1-mixed-failure-taxonomy"

LATEX_CATEGORY_ORDER: tuple[str, ...] = (
    "acceptance_mismatch",
    "replay_failure",
    *(category for category in TAXONOMY_CATEGORIES if category not in {"acceptance_mismatch", "replay_failure"}),
)

_AGGREGATED_SECTION = "## Aggregated taxonomy"
_TABLE_ROW_RE = re.compile(
    r"^\|\s*`([^`]+)`\s*\|\s*(\d+)\s*\|\s*([0-9.]+%?)\s*\|\s*$"
)


@dataclass(frozen=True, slots=True)
class TaxonomyTableRow:
    """One row of an aggregate failure taxonomy table."""

    category: str
    count: int
    percentage: float


def parse_failure_taxonomy_report_md(text: str) -> list[TaxonomyTableRow]:
    """Parse the aggregate taxonomy table from a Markdown report."""
    section = _extract_aggregated_section(text)
    rows: list[TaxonomyTableRow] = []
    for line in section.splitlines():
        match = _TABLE_ROW_RE.match(line.strip())
        if not match:
            continue
        category, count_text, percentage_text = match.groups()
        rows.append(
            TaxonomyTableRow(
                category=category,
                count=int(count_text),
                percentage=_parse_percentage(percentage_text),
            )
        )
    if not rows:
        raise ValueError("no aggregate taxonomy rows found in report markdown")
    return rows


def taxonomy_rows_for_latex(rows: list[TaxonomyTableRow]) -> list[TaxonomyTableRow]:
    """Return rows in export order, inserting zero-count categories if missing."""
    by_category = {row.category: row for row in rows}
    unknown = sorted(set(by_category) - set(LATEX_CATEGORY_ORDER))
    if unknown:
        raise ValueError(f"unexpected taxonomy categories in report: {', '.join(unknown)}")

    ordered: list[TaxonomyTableRow] = []
    for category in LATEX_CATEGORY_ORDER:
        if category in by_category:
            ordered.append(by_category[category])
        else:
            ordered.append(TaxonomyTableRow(category=category, count=0, percentage=0.0))
    return ordered


def render_failure_taxonomy_latex_table(
    rows: list[TaxonomyTableRow],
    *,
    caption: str = DEFAULT_LATEX_CAPTION,
    label: str = DEFAULT_LATEX_LABEL,
) -> str:
    """Render a booktabs LaTeX table for aggregate failure taxonomy counts."""
    ordered = taxonomy_rows_for_latex(rows)
    lines = [
        "% Auto-generated by fsmreasonbench.cli.export_failure_taxonomy_table",
        "\\begin{table}[t]",
        "\\centering",
        f"\\caption{{{_latex_text(caption)}}}",
        f"\\label{{{label}}}",
        "\\begin{tabular}{lrr}",
        "\\toprule",
        "Category & Count & Percentage \\\\",
        "\\midrule",
    ]
    for row in ordered:
        lines.append(
            f"\\texttt{{{_latex_category(row.category)}}} & "
            f"{row.count} & {_fmt_latex_percentage(row.percentage)} \\\\"
        )
    lines.extend(["\\bottomrule", "\\end{tabular}", "\\end{table}", ""])
    return "\n".join(lines)


def export_failure_taxonomy_latex(
    report_path: str | Path,
    out_tex: str | Path,
    *,
    caption: str = DEFAULT_LATEX_CAPTION,
    label: str = DEFAULT_LATEX_LABEL,
) -> Path:
    """Parse a Markdown report and write a LaTeX table."""
    report_path = Path(report_path)
    if not report_path.is_file():
        raise FileNotFoundError(f"report not found: {report_path}")

    rows = parse_failure_taxonomy_report_md(report_path.read_text(encoding="utf-8"))
    latex = render_failure_taxonomy_latex_table(rows, caption=caption, label=label)

    out_path = Path(out_tex)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(latex, encoding="utf-8")
    return out_path


def _extract_aggregated_section(text: str) -> str:
    if _AGGREGATED_SECTION not in text:
        raise ValueError(f"missing {_AGGREGATED_SECTION!r} section in report markdown")
    tail = text.split(_AGGREGATED_SECTION, maxsplit=1)[1]
    if "\n## " in tail:
        tail = tail.split("\n## ", maxsplit=1)[0]
    return tail


def _parse_percentage(value: str) -> float:
    cleaned = value.strip().removesuffix("%")
    return float(cleaned)


def _latex_text(value: str) -> str:
    return (
        value.replace("\\", "\\textbackslash{}")
        .replace("&", "\\&")
        .replace("%", "\\%")
        .replace("_", "\\_")
    )


def _latex_category(value: str) -> str:
    return value.replace("_", "\\_")


def _fmt_latex_percentage(value: float) -> str:
    return f"{value:.1f}\\%"
